# Uncomment the next line to define a global platform for your project
platform :osx, '10.14'

target 'VTXScannerLaptimer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'VTXScannerLaptimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VTXScannerLaptimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
